version: '3.8'

services:
  translation-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: flask-translation-service-gpu
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - GGUF_FILE=models/LLaMAX3-8B-Alpaca.Q8_0.gguf
      - N_GPU_LAYERS=-1
      - N_THREADS=8
      - PORT=5000
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
